### ISSUE TITLE
The project dont work

### ISSUE THREAD

**Issue by Jeferson-Oliveira** [igorkulman/OpenALPR.Lib#1]
Hello, i get a problem when i try to run this project, the visual studio says "FileNotFundException" for the openalpr-net.dll, i tried to download again the archive and put the file in directory and refecence then, but a do not have a sucessfull. can you help me?

**Comment by igorkulman** [comment]
I guess you are trying to run the console app in AnyCPU configuration. You have to run it in x64.

**Comment by Jeferson-Oliveira** [comment]
Thanks worked , but this version ( openalpr - net.dll ) is outdated , you could upgrade? or explain how to do?

**Comment by igorkulman** [comment]
I think replacing the current DLLs inhttps://github.com/igorkulman/OpenALPR.Lib/tree/master/OpenALPR.Lib/openalpr with the newer ones should be enough.

**Comment by Jeferson-Oliveira** [comment]
![image](https://cloud.githubusercontent.com/assets/14915772/14972741/add33bae-10b5-11e6-82e8-f0d530c27610.png)
I replaced the dlls, but now i get the error in AlprNet class, i tried edit but i can't to do this, i guess that the class is blocked for editing.

**Comment by igorkulman** [comment]
I updated the code to the latest OpenALPR.Lib (x64).

**Comment by Jeferson-Oliveira** [comment]
Thanks, for your help, i want create WP aplication and use this library, i want get a Bitmap image from an webcam and pass to the library and recognize the number plates, how i can todo this(as you do in console application) ?

**Comment by igorkulman** [comment]
You do not, there is no OpenALPR.Lib for Windows Phone.

**Comment by Jeferson-Oliveira** [comment]
Sorry rsrs, i wanted say Windows Forms Application, can you help me?, i tried yesterday with you new version of the code but a dont get success.
Ps: sorry my english is bad i hope that you understand me.

**Comment by igorkulman** [comment]
So create a WinForms app .. I will not write it for you.

**Comment by Jeferson-Oliveira** [comment]
I just need build de OpenALPR, and add a reference to the OpenALPR.dll that is located in "OpenALPR.Lib-master\OpenALPR.Lib\bin\x64\Debug" in my WinForm Application,that is right?
